'use client';

import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

const TERMS_OF_SERVICE_CONTENT = `
# Terms of Use

Last updated: 10 September 2025

Welcome to https://www.archestra.ai (together with its subdomains, Content, Marks and services, Desktop Application, collectively the “Site”). These Terms constitute a binding legal agreement between you (“you”) and Archestra Inc. (“Archestra”, “we”, “our” or “us”) and govern (a) your access and use of the Site; and (b) your access and use of the Archestra services, which is an open-source MCP AI orchestration platform both web and desktop (“Platform”) (the Site together with the Platform shall be referred hereinafter as the “Services”).

By accessing or using the Site or by signing in or registering to the Platform, you expressly acknowledge and agree that you are entering a legal agreement with us and have understood and agree to comply with, and be legally bound by, these Terms of Use, together with the Privacy Policy (the “Terms”). If you don't accept these terms, you must not click I agree/Sign Up" (or the similar button or checkbox), and you are not authorized to access or use any part of the Site and the Services. An individual entering into these Terms on your behalf represents that he/she has the right, authority and capacity to act on your behalf and to bind you to this Agreement.

We reserve the right to unilaterally amend these Terms at any time by posting the modified version at [https://www.archestra.ai/terms]. In such cases, we will provide you with notice through a pop-up or banner within the service, by sending an email (or other written notice) to you, or through other similar mechanisms. The modified Terms shall become effective and binding seven (7) days following such notification (unless the notification specifies a later effective date). and your continued use of the Site thereafter means that you accept those modifications.

You hereby waive any applicable rights to require an original (non-electronic) signature or delivery or retention of non-electronic records, to the extent not prohibited under applicable law. If you do not agree to be bound by these Terms please do not access or use the Site.

Background
The Site is intended to provide you information on Archestra and its Services.

Ability to Accept Terms
The Site is only intended for individuals aged 18 years or older. If you are not 18 years old, please don’t make use of our Site without the authorization of your parents or guardians.

Site Access. For such time as these Terms are in effect, we hereby grant you permission to visit and use the Site provided that you comply with these Terms and applicable law.
Restrictions. As a condition to your right to access and use the Site, you shall not (and shall not permit or encourage any third party to) do any of the following: (a) copy or reproduce the Site; (b) sell, assign, lease, lend, rent, distribute, or make available the Site to any third party, or otherwise offer or use the Site in a time-sharing, outsourcing, or service bureau environment; (c) modify, alter, adapt, arrange, translate, decompile, disassemble, reverse engineer, decrypt, or otherwise attempt to discover the source code or non-literal aspects (such as the underlying ideas, algorithms, structure, sequence, organization, and interfaces) of, the Site; (d) remove, alter, or conceal, in whole or in part, any copyright, trademark, or other proprietary rights notice or legend displayed or contained on or in the Site; (e) circumvent, disable or otherwise interfere with security-related or technical features or protocols of the Site; (f) make a derivative work of the Site, or use the Site to develop any service or product that is the same as (or substantially similar to or competitive with) the Site; (g) publish or transmit any robot, virus, malware, Trojan horse, spyware, or similar malicious item intended (or that has the potential) to damage or disrupt the Site; (i) take any action that imposes or may impose (at our sole discretion) an unreasonable or disproportionately large load on the Site infrastructure, or otherwise interfere (or attempt to interfere) with the integrity or proper working of the Site; and/or (j) use the Site to infringe, misappropriate or violate any third party's Intellectual Property Rights (as defined below), or any law.
Account.  In order to use some of the services of the Site, you may have to create an account ("Account") by connecting your Gmail or GitHub account.  You agree not to create an Account for anyone else or use the account of another without their permission. You must notify Archestra immediately of any breach of security or unauthorized use of your Account. As between you and Archestra, you are solely responsible and liable for the activity that occurs in connection with your Account.  If you wish to delete your Account, you may send an email request to Archestra at matvey@archestra.ai.
Subscription to the Platform. Subject to your compliance with these Terms and payment of applicable fees specified in your order, if and as applicable, Archestra hereby grants you a non-exclusive, non-transferable, non-sublicensable, and revocable right to remote access (including on a SaaS basis) to the Platform during the Term (as defined below), solely for your internal purposes.
Subscription Fees. Your access to and use of the Platform may be subject to payment of the subscription fees. Unless stated otherwise (i) prior to the commencement of a renewal term specified in the Subscription Order, we reserve the right to change our subscription fees and you shall be informed of such changes via an email and/or a notification on the Platform prior to such changes; (ii) all fees are stated, and shall be paid, in US Dollars, are non-refundable and are exclusive of all taxes, levies, or duties, which are your responsibility.
Term and Termination. We may stop to provide the Platform to you at any time, including in the event that you breach these Terms. In case we cease to provide you with the Platform during your subscription not as a result of your breach of these Terms, your sole remedy and our sole liability to you, will be to provide you with a refund for any amount pre-paid for the remaining unused duration of the Platform. Upon termination or expiration of these Terms: (i) the license granted to you under these Terms shall expire, and you shall discontinue any further use and access thereof; and (ii) you shall immediately delete and dispose of all copies of the Content in your or your representatives’ possession or control.
Intellectual Property Rights
Content and Marks. The Site is not for sale and is Archestra’s sole property. All right, title, and interest, including any intellectual property rights evidenced by or embodied in the: (i) content on the Site, including without limitation, the text, documents, articles, brochures, descriptions, products, software, graphics, photos, sounds, videos, interactive features, any other information and services (collectively, the “Content”); and (iii) the trademarks, service marks and logos contained therein (“Marks”), are the exclusive property of Archestra and/or its licensors (as relevant) and may be protected by applicable copyright or other intellectual property laws and treaties. "Archestra logo" and other marks are Marks of Archestra or its affiliates. All other trademarks, service marks, and logos used on the Site are the trademarks, service marks, or logos of their respective owners. We reserve all rights not expressly granted in and to the Site and the Content and to any part of them.
Use of Content. Content on the Site is provided to you for your information and personal use only and may not be used, modified, copied, distributed, transmitted, broadcast, displayed, sold, licensed, de-compiled, or otherwise exploited for any other purposes whatsoever without our prior written consent. If you download or print a copy of the Content you must retain all copyright and other proprietary notices contained therein.
Any anonymous information, which is derived from the use of the Site (i.e., metadata, aggregated and/or analytics information and/or intelligence relating to the operation, support, and/or your use, of the Site) which is not personally identifiable information (“Analytics Information”) may be used by Archestra for providing the Site and its related services, for development, improving the Site and/or for statistical purposes. Such Analytics Information is Archestra exclusive property.
User Submissions
Responsibility.  The Site may permit the submission, hosting, sharing and publishing of content by you and other users ("User Submissions").  You understand that whether or not such User Submissions are published, we do not guarantee any confidentiality with respect to any User Submissions.  You shall be solely responsible for your User Submissions and the consequences of posting, publishing or uploading them.  We have complete discretion whether to publish your User Submissions and we reserve the right in our sole discretion and without further notice to you, to monitor, censor, edit, remove, delete, and/or remove any and all Content posted on the Site (including User Submissions) at any time and for any reason.

Ownership
You represent and warrant that you own or have the necessary rights and permissions to use and authorize Archestra to use all Intellectual Property Rights (defined below) in and to your User Submissions, and to enable inclusion and use thereof as contemplated by the Site and these Terms. Unless the User Submissions are separately referred to, all references herein to Content shall include references to User Submissions.  "Intellectual Property Rights" means any and all rights, titles, and interests (under any jurisdiction or treaty, whether protectable or not, and whether registered or unregistered) in and to technology and other intellectual property (such as the Content), and includes without limitation patents, copyright and similar authorship rights, personal rights (such as moral rights, rights of privacy, and publicity rights), architectural, building and location (and similar geography-based) rights, mask work rights, trade secret and similar confidentiality rights, design rights, industrial property rights, trademark, trade name, trade dress and similar branding rights, as well as: (a) all applications, registrations, renewals, extensions, continuations, continuations-in-part, divisions or reissues of the foregoing rights; and (b) all goodwill associated with the foregoing rights.

License to User Submissions. By submitting the User Submissions to Archestra, you hereby grant Archestra a worldwide, irrevocable, non-exclusive, royalty-free, perpetual, sublicensable and transferable license to use, reproduce, distribute, prepare derivative works of, display, and perform the User Submissions in connection with the Site and Archestra's business, including without limitation for publishing and redistributing part or all of your User Submissions (and derivative works thereof) in any media formats and through any media channels and, and you hereby waive any moral rights in your User Submissions, to the extent permitted by law. You also hereby grant each user of the Site or other viewer or user of the User Submission a non-exclusive right to use, reproduce, distribute, prepare derivative works of, display and perform such User Submissions, all in accordance with these Terms.
Prohibited Content. You agree that you will not display, post, submit, publish, upload or transmit a User Submission that: (i) is unfair or deceptive under the consumer protection laws of any jurisdiction; (ii) is copyrighted, protected by trade secret or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights; (iii) creates a risk to a person’s safety or health, creates a risk to public safety or health, compromises national security, or interferes with an investigation by law enforcement; (iv) impersonates another person; (v) promotes illegal drugs, violates export control laws, relates to illegal gambling, or illegal arms trafficking; (vi) is unlawful, defamatory, libelous, threatening, pornographic, harassing, hateful, racially or ethnically offensive, or encourages conduct that would be considered a criminal offense, gives rise to civil liability, violates any law, or is inappropriate; (vii) involves theft or terrorism; or (viii) is otherwise malicious or fraudulent.
Exposure. You understand and acknowledge that when accessing and using the Site: (i) you will be exposed to User Submissions from a variety of sources, and that Archestra is not responsible for the accuracy, usefulness, safety, or Intellectual Property Rights of, or relating to, such User Submissions; and (ii) you may be exposed to User Submissions that are inaccurate, offensive, indecent, or objectionable. You hereby agree to waive, and hereby do waive, any legal or equitable rights or remedies you may have against Archestra with respect to (i) and (ii) herein.
Spam. You agree not to, and will not, use the communications systems provided by the Site to send unauthorized commercial communications and you shall be solely responsible and liable for any such unauthorized communications.
Data Sharing. While using the Services, certain data, such as personal data or other data, will be made available and/or accessible to KeArchestraep or the Services directly from you or via third parties tools and platforms to which you have granted Archestra access (the " Data"). You hereby grant Archestra a worldwide, non-exclusive, non-assignable (except as provided herein), non-sublicensable (except to Company's subcontractors, if applicable), non-transferable right and license, to access and use the Data, including without limitation for Archestra's provision of the Services and related services hereunder. As the exclusive owner of the Data, You hereby represent warrants and covenants that to the extent the Data includes any personally identifiable information, You have received and/or obtained any and all required consents or permits and have acted in compliance with any and all applicable privacy laws, including, without limitation privacy laws, as to allow us to receive, transfer and use the Data solely in order to perform the Service. To the extent that You need a data processing agreement, You may request us to provide it with Archestra's Data Processing Agreement ("DPA") and shall return such DPA signed to Archestra as described therein.
Information Description
We attempt to be as accurate as possible. However, we cannot and do not warrant that the Content available on the Site is accurate, complete, reliable, current, or error-free. We reserve the right to make changes in or to the Content, or any part thereof, in our sole judgment, without the requirement of giving any notice prior to or after making such changes to the Content. Your use of the Content, or any part thereof, is made solely at your own risk and responsibility.

Disclosure
We reserve the right to access, read, preserve, and disclose any information that we obtain in connection with the Site, and your use thereof, as we reasonably believe is necessary to: (i) satisfy any applicable law, regulation, legal process, subpoena or governmental request; (ii) enforce these Terms, including to investigate potential violations of them; (iii) detect, prevent or otherwise address fraud, security or technical issues; (iv) respond to user support requests; or (v) protect the rights, property or safety of Archestra, its users or the public.

Links. Third Party Content.
The Site may contain links, and may enable you to post content, to third party websites that are not owned or controlled by Archestra. We are not affiliated with, have no control over, and assume no responsibility for the content, privacy policies, or practices of, any third party websites. You: (i) are solely responsible and liable for your use of and linking to third party websites and any content that you may send or post to a third party website; and (ii) expressly release Archestra from any and all liability arising from your use of any third party website. Accordingly, we encourage you to read the terms and conditions and privacy policy of each third party website that you may choose to visit.

`;

export default function TermsContent() {
  return (
    <ReactMarkdown
      remarkPlugins={[remarkGfm]}
      components={{
        p: ({ node, ...props }) => <p {...props} className="text-base text-gray-700 leading-relaxed mb-4" />,
        h1: ({ node, ...props }) => <h1 {...props} className="text-4xl font-bold text-gray-900 mb-8" />,
        h2: ({ node, ...props }) => <h2 {...props} className="text-2xl font-semibold text-gray-900 mb-4 mt-8" />,
        h3: ({ node, ...props }) => <h3 {...props} className="text-xl font-semibold text-gray-900 mb-3 mt-6" />,
        ul: ({ node, ...props }) => <ul {...props} className="list-disc list-inside mb-4 space-y-2 pl-4" />,
        ol: ({ node, ...props }) => <ol {...props} className="list-decimal list-inside mb-4 space-y-2 pl-4" />,
        li: ({ node, ...props }) => <li {...props} className="text-base text-gray-700 leading-relaxed" />,
        a: ({ node, ...props }) => <a {...props} className="text-blue-600 hover:underline" />,
        strong: ({ node, ...props }) => <strong {...props} className="font-semibold text-gray-900" />,
        blockquote: ({ node, ...props }) => (
          <blockquote {...props} className="border-l-4 border-gray-300 pl-6 my-6 text-base text-gray-600 italic" />
        ),
      }}
    >
      {TERMS_OF_SERVICE_CONTENT}
    </ReactMarkdown>
  );
}
