name: Setup node/pnpm + install frontend dependencies
description: Setup node/pnpm + install frontend dependencies
runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        version: 10.13.1

    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: "24.4.1"
        cache: "pnpm"
        cache-dependency-path: desktop_app/pnpm-lock.yaml

    - name: Install dependencies
      shell: bash
      run: cd desktop_app && pnpm install --frozen-lockfile --prefer-offline
